### ISSUE TITLE
Join Mattermost integrations community channel?

### ISSUE THREAD

**Issue by jasonblais** [Schoaf/qa-mattermost-notifications#1]
Hi @Schoaf,

Thank you for sharing your project with us, great work with the Question2Answer integration! 

We'd also like to welcome you to join the [integrations community channel on our nightly builds server](https://pre-release.mattermost.com/core/channels/integrations), if you're not a member yet.

Wonderful work! Can't wait to share it with the rest of the Mattermost community!

**Comment by Schoaf** [comment]
Thanks! :-)
